socialmedia/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

socialmedia/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    
    # url will be something like posts/by/user's slug pattern
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    
    # url -> posts/by/user's slug/post_id
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    
    # url -> posts/delete/post_id
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

socialmedia/socialmedia/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r"^accounts/", include('accounts.urls', namespace='accounts')),
    url(r"^accounts/", include('django.contrib.auth.urls')),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    
    
    
]

socialmedia/groups/models.py
from django.db import models
# slugify helps in making normal sentences as links by adding 
# underscores in place of spaces and making everything lowercase
# and removing unwanted chars.
from django.utils.text import slugify

from django.core.urlresolvers import reverse

# Groups models.py
# Create your models here.

# misaka is used for markdows inside of posts
import misaka

# get_user_model helps in grabbing the current user in the current user 
# session
from django.contrib.auth import get_user_model
User = get_user_model()

# this is to use custom template tags used in posts/templates/posts/post_list.html
# it allows to grab the details from this model to give to that app
# specifically here inside GroupMember model, user_group can be grabbed by 
# get_user_group inside that post_list.html tempalte
from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships")
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

socialmedia/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group,GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

#whenever a user clicks on join group, things should happen in the backend to 
# make that user a member of that group and he must be redirected to anohter page,
# hence, the RedirectView class extension is needed.
class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        # redirect to the group page, and which specific group is that ? 
        # we need the slug of that group to identify it.
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    # in case the user is already member of that group
    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            # the save method is not being used here.
            # for that, we needed = group_mem_obj = GroupMember(user, group)
            # group_mem_obj.save()
            
            # create method is used to create and save the object in the 
            # database at the same time
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

socialmedia/groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock pregroup %}
            {% block group_content %}{% endblock group_content %}
            {% block postgroup %}{% endblock postgroup %}
        </div>
    </div>
{% endblock content %}

socialmedia/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    {% comment %} from the class based views, a context dictionary is passed on by
    them and we can use it's object, ie. group in this case  {% endcomment %}
    <h1>{{ group.name }}</h1>
    <h2>Member Count : {{ group.members.count }}</h2>

    <div class='content'>
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" 
                class="btn btn-lg btn-fill btn-warning">
                <span class='glyphicon glyphicon-remove-circle' ></span>Leave</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" 
                class="btn btn-lg btn-fill btn-warning">
                <span class='glyphicon glyphicon-ok-circle' ></span>Join</a>
        {% endif %}
    </div>
{% endblock pregroup %}


{% block group-content %} 
    <div class='col-md-8'>
        {% if group.posts.count == 0 %}
            <h1>No posts in this group yet</h1>
        {% else %}
            {% for post in group.posts.all %}
                {% comment %} instead of extending to inject content from another html, we can directly 
                inject content inline by using include command like shown below {% endcomment %}
                {% comment %} the _ signifies that this is an html which is injected here {% endcomment %}
                {% include 'posts/_post.html' %} 
            {% endfor %}
        {% endif %}
    </div>
{% endblock group-content %} 

socialmedia/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% block group-content %}
    <h2>Create a new group !</h2>
    <form action="{% url 'groups:create' %}" method="POST", id='groupForm'>
        {% csrf_token %}

        {% bootstrap_form form %}
        <input type="submit" value="Create" class='btn btn-primary btn-large'>
    </form>
{% endblock group-content %}

socialmedia/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>Welcome Back !
                    <a href="{% url 'posts:for_user' username=user.username %}">
                    @{{ user.username }}
                    </a>
                </h2>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>
        </div>
        {% if user.is_authenticated %}
            {% comment %} if someone wants to create a new group, they will be redirected to groups:create
            and that'll be created by the CreateView in our views.py and we need to set
            that up via group_form.html {% endcomment %}
            <a href="{% url 'groups:create' %}" class='btn btn-md btn-fill btn-warning'>
                <span class='glyphicon glyphicon-plus-sign'></span>Create New Group !
            </a>
        {% endif %}
    </div>
{% endblock pregroup %}


{% block group-content %}

    <div class='col-md-8'>
        <div class="list-group">
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}" class='list-group-item' >
                    <h3 class='title list-group-item-heading'>{{ group.name }}</h3>
                    <div class='list-group-item-text container-fluid'>
                        {{ group.description_html|safe }}
                        <div class="row">
                            <div class="col-md-4">
                                <span class='badge'>{{ group.members.count }}</span>
                                member{{ group.members.count|pluralize }}
                            </div>
                            <div class="col-md-4">
                                <span class='badge'>{{ group.posts.count }}</span>
                                member{{ group.posts.count|pluralize }}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

{% endblock group-content %}